export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USER_DATA = 'GET_USER_DATA';

export const GET_SENSORS = 'GET_SENSORS';
export const DELETE_SENSOR = 'DELETE_SENSOR';
export const ADD_SENSOR = 'ADD_SENSOR';
export const UPDATE_SENSOR = 'UPDATE_SENSOR';
export const GET_SENSOR_DATA = 'GET_SENSOR_DATA';
export const GET_CHART_DATA = 'GET_CHART_DATA';
export const POST_CSV = 'POST_CSV';

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_CAMERAS = 'GET_CAMERAS';
export const ADD_CAMERA = 'ADD_CAMERA';
export const DELETE_CAMERA = 'DELETE_CAMERA';
export const UPDATE_CAMERA = 'UPDATE_CAMERA';
export const GET_CAMERA_DATA = 'GET_CAMERA_DATA';

export const GET_CONTROLLERS = 'GET_CONTROLLERS';
export const ADD_CONTROLLER = 'ADD_CONTROLLER';
export const DELETE_CONTROLLER = 'DELETE_CONTROLLER';
export const UPDATE_CONTROLLER = 'UPDATE_CONTROLLER';
export const GET_CONTROLLER_DATA = 'GET_CONTROLLER_DATA';
export const RUN_CONTROLLER = 'RUN_CONTROLLER';

export const SEND_TOKEN = 'SEND_TOKEN';
export const GET_FIREBASE_TOKEN = 'GET_FIREBASE_TOKEN';

export const GET_ACTIONS = 'GET_ACTIONS';
export const ADD_ACTION = 'ADD_ACTION';
export const DELETE_ACTION = 'DELETE_ACTION';